version: '3.8'

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio
  command: server --console-address ":9001" http://minio{1...3}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: 'admin'
    MINIO_ROOT_PASSWORD: 'changeme'
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  # minio instances
  # ---------------
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./data/1-1:/data1
      - ./data/1-2:/data2
  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ./data/2-1:/data1
      - ./data/2-2:/data2
  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - ./data/3-1:/data1
      - ./data/3-2:/data2

  # edge server touchpoint
  #-----------------------
  nginx:
    build: ./nginx
    depends_on:
      - minio1
      - minio2
      - minio3
    ports:
      - 80:80
      - 9000:9000
      - 9001:9001